import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "@next/font/local";

const font = localFont({
  src: "../../public/fonts/PramukhRounded-Bold.otf",
  variable: "--faction",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "sarvagk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
